services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: build.abdilla.my.id/api.abdilla.my.id-bookmark-sync-thumbnail:v1.0.0
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - abdilla.my.id
networks:
  abdilla.my.id:
    external: true
