services:
  api-bookmark-sync-thumbnail:
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - abdilla.my.id
networks:
  abdilla.my.id:
    external: true
